#!/usr/bin/env bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
IGNORE="$SCRIPTDIR/.ignore"

fzf_command='fzf'
fd_command="fd . ${HOME}/.mail/ --ignore-file=${IGNORE} --type d"

folder="$($fd_command | $fzf_command)"

echo "push 'c$folder<enter>'"
